name: Python
on:
  schedule:
  - cron: "*/5 * * * *"
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        
        - name: checkout repo content
          uses: actions/checkout@v2 # checkout the repository content to github runner.
        - name: PHP Runner
          uses: franzliedke/gh-action-php@0.3.0
        - name: setup python
          uses: actions/setup-python@v2
          with:
              python-version: 3.8 #install the python needed
        - name: execute py script # run the run.py to get the latest data
          run: |
              php status.php start-workflow
              python run.py
              
        - name: commit files
          run: |
                git config --local user.email "fbiego.fb@gmail.com"
                git config --local user.name "fbiego"
                git add -A
                git commit -m "update data" -a
        
        - name: push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main  
      
    notification:
      name: Notify
      runs-on: ubuntu-18.04
      needs: [build]
      if: always()
      steps: 
        - uses: martialonline/workflow-status@v2
          id: check
        - run: php status.php failed
          if: steps.check.outputs.status == 'failure'
        - run: php status.php cancelled
          if: steps.check.outputs.status == 'cancelled'
        - run: php status.php success
          if: steps.check.outputs.status == 'success'
          
